/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSetupRouteImport } from './routes/app.setup'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppInvitationsRouteImport } from './routes/app.invitations'
import { Route as AppSplatRouteImport } from './routes/app.$'
import { Route as AppVerificationsIndexRouteImport } from './routes/app.verifications.index'
import { Route as AppPeopleIndexRouteImport } from './routes/app.people.index'
import { Route as AppVerificationsIdRouteImport } from './routes/app.verifications.$id'
import { Route as AppPeopleIdRouteImport } from './routes/app.people.$id'
import { Route as AppInvitationsIdRouteImport } from './routes/app.invitations.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInvitationsRoute = AppInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppVerificationsIndexRoute = AppVerificationsIndexRouteImport.update({
  id: '/verifications/',
  path: '/verifications/',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AppRoute,
} as any)
const AppVerificationsIdRoute = AppVerificationsIdRouteImport.update({
  id: '/verifications/$id',
  path: '/verifications/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIdRoute = AppPeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInvitationsIdRoute = AppInvitationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInvitationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/$': typeof AppSplatRoute
  '/app/invitations': typeof AppInvitationsRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/setup': typeof AppSetupRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
  '/app/invitations/$id': typeof AppInvitationsIdRoute
  '/app/people/$id': typeof AppPeopleIdRoute
  '/app/verifications/$id': typeof AppVerificationsIdRoute
  '/app/people/': typeof AppPeopleIndexRoute
  '/app/verifications/': typeof AppVerificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/$': typeof AppSplatRoute
  '/app/invitations': typeof AppInvitationsRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/setup': typeof AppSetupRoute
  '/app/team': typeof AppTeamRoute
  '/app': typeof AppIndexRoute
  '/app/invitations/$id': typeof AppInvitationsIdRoute
  '/app/people/$id': typeof AppPeopleIdRoute
  '/app/verifications/$id': typeof AppVerificationsIdRoute
  '/app/people': typeof AppPeopleIndexRoute
  '/app/verifications': typeof AppVerificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/$': typeof AppSplatRoute
  '/app/invitations': typeof AppInvitationsRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/setup': typeof AppSetupRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
  '/app/invitations/$id': typeof AppInvitationsIdRoute
  '/app/people/$id': typeof AppPeopleIdRoute
  '/app/verifications/$id': typeof AppVerificationsIdRoute
  '/app/people/': typeof AppPeopleIndexRoute
  '/app/verifications/': typeof AppVerificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/$'
    | '/app/invitations'
    | '/app/notifications'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/setup'
    | '/app/team'
    | '/app/'
    | '/app/invitations/$id'
    | '/app/people/$id'
    | '/app/verifications/$id'
    | '/app/people/'
    | '/app/verifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/$'
    | '/app/invitations'
    | '/app/notifications'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/setup'
    | '/app/team'
    | '/app'
    | '/app/invitations/$id'
    | '/app/people/$id'
    | '/app/verifications/$id'
    | '/app/people'
    | '/app/verifications'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/$'
    | '/app/invitations'
    | '/app/notifications'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/setup'
    | '/app/team'
    | '/app/'
    | '/app/invitations/$id'
    | '/app/people/$id'
    | '/app/verifications/$id'
    | '/app/people/'
    | '/app/verifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invitations': {
      id: '/app/invitations'
      path: '/invitations'
      fullPath: '/app/invitations'
      preLoaderRoute: typeof AppInvitationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$': {
      id: '/app/$'
      path: '/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verifications/': {
      id: '/app/verifications/'
      path: '/verifications'
      fullPath: '/app/verifications/'
      preLoaderRoute: typeof AppVerificationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/people/': {
      id: '/app/people/'
      path: '/people'
      fullPath: '/app/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verifications/$id': {
      id: '/app/verifications/$id'
      path: '/verifications/$id'
      fullPath: '/app/verifications/$id'
      preLoaderRoute: typeof AppVerificationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/people/$id': {
      id: '/app/people/$id'
      path: '/people/$id'
      fullPath: '/app/people/$id'
      preLoaderRoute: typeof AppPeopleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invitations/$id': {
      id: '/app/invitations/$id'
      path: '/$id'
      fullPath: '/app/invitations/$id'
      preLoaderRoute: typeof AppInvitationsIdRouteImport
      parentRoute: typeof AppInvitationsRoute
    }
  }
}

interface AppInvitationsRouteChildren {
  AppInvitationsIdRoute: typeof AppInvitationsIdRoute
}

const AppInvitationsRouteChildren: AppInvitationsRouteChildren = {
  AppInvitationsIdRoute: AppInvitationsIdRoute,
}

const AppInvitationsRouteWithChildren = AppInvitationsRoute._addFileChildren(
  AppInvitationsRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppInvitationsRoute: typeof AppInvitationsRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSetupRoute: typeof AppSetupRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPeopleIdRoute: typeof AppPeopleIdRoute
  AppVerificationsIdRoute: typeof AppVerificationsIdRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
  AppVerificationsIndexRoute: typeof AppVerificationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppInvitationsRoute: AppInvitationsRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSetupRoute: AppSetupRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
  AppPeopleIdRoute: AppPeopleIdRoute,
  AppVerificationsIdRoute: AppVerificationsIdRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
  AppVerificationsIndexRoute: AppVerificationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
